### PR TITLE
Updates boost.cyg

### PR DESCRIPTION
**Pull request by Halolegend94**
Specifies the python development library needed to build python bindings

### CODE REVIEW

**Comment by Halolegend94** [comment]
Also, add newer compilers to the list.

**Comment by Halolegend94** [comment]
It compiles successfully on my local folder.

**Review by marcodelapierre — APPROVED** [review]
Super cool!

**Comment by marcodelapierre** [comment]
Shall you look into implementing these changes in the other boost cygnets, too? (sles, cle, mwa)

**Comment by Halolegend94** [comment]
> Shall you look into implementing these changes in the other boost cygnets, too? (sles, cle, mwa)

Yes Marco, thanks for the reminder. I will do it and push a commit to this pull request's branch

**Pull request merged**
