### PR TITLE
Cristian contrib

### PR DESCRIPTION
**Pull request by Halolegend94**
Adds lot of cynget files, mainly:

- gdb for topaz
- lammps for magnus
- simplify boost cygnet files (warning: due to problems with intel compilers, intel compilation on mangus and topaz doesn't work currently)
- cygnet files for radioastronomy packages for topaz (used to build software stack for pacer project "BLINK").

### CODE REVIEW

**Comment by Halolegend94** [comment]
Before you say anything Marco, Ill have to double check that I have set MPI as a compiler rather than a dependency. I guess it is the same for MPICH

**Comment by marcodelapierre** [comment]
Going through the cygnets. 
I am assuming you've tested them, so I am leaving comments from a best practices perspective:
- aoflagger, cotter, libsigcpp, libxml2, wsclean: the WHATIS description needs updating (currently it has info for another package, gsl)
- erfa, gdb, idg, pal: in the WHATIS in these cygnets, can you add the reference url (format: "For further information see ")
- MAALI_TOOL_TYPE: consider if any of these packages should go under "apps" (applications or libraries) or "tools" (utilities), rather than "devel" (developer tools).
- GDB silly question: does it need to be built with each compiler version? wouldn't the system compiler be enough?
- libsigcpp: this looks like a "performance" library to me, so I wouldn't put MAALI_DEFAULT_SYSTEM_GCC as the compiler, but instead use either MAALI_DEFAULT_COMPILERS, or the list of them (gcc/8.3.0) as you did in other cygnets in this PR
- cle60up07/boost.cyg: out of curiosity, have you used the cygnet under `maali-cygnet/Archived/cle60up05/` as a reference?
- lammps: you don't need this `export CRAYPE_LINK_TYPE=dynamic`, it's done by maali :)

**Review by marcodelapierre — CHANGES_REQUESTED** [review]
please address comments in the conversation tab

**Comment by Halolegend94** [comment]
Hi Marco, thanks for taking the time to review my pull request. I have fixed all the problems.

Thanks!

**Review by marcodelapierre — APPROVED** [review]
thanks Cristian, good to go for me!
please go ahead with merging when convenient for you.

**Pull request merged**
