### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Halolegend94**
Adds aplpy cygnet
The version added previously is corrupted. I had set up a script to download some packages from the archived foler up05 but the cygnet file for aplpy was not present in the mentioned folder. This one was copied from up04 If I remember well.

### CODE REVIEW

**Comment by dgrimreaper** [comment]
can we do this without using pip please?  Researchers must know the version of all software used so that their research is reproducible, and pip is terrible for that.  Running this install on a different day may result in a different install.

**Comment by marcodelapierre** [comment]
Two points of feedback:
1) [my ignorance here] when you download a python package from source as we do in this cygnet, is then "pip install" using it for the installation? (hopefully yes)
2) we can make the usage of pip more acceptable, if EVERY SINGLE package (including dependencies) that pip installs comes with a version specification. This can be achieved with a syntax like: `pip install aplpy==2.0.3`

**Comment by Halolegend94** [comment]
once you download a package you dont need pip to install it. pip itself will move into the root folder of the package and call `python setup.py install`. I am working on fixing this installation now.

**Comment by marcodelapierre** [comment]
thanks, please also double check that the package is not downloading any "unversioned" dependencies during installation..ideally those will need to be versioned by us, as Daniel suggests

**Comment by Halolegend94** [comment]
So basically I am going to write a cygnet file for every prerequisite. One of these,[ astropy](https://github.com/PawseySC/maali-cygnet/blob/492921dfe95269ed9674e33438c0c77dc608819a/mwa_sles12sp4/astropy.cyg), looks like a nightmare itself. Moreover, the cygnet file looks pretty old. Some packages that appear in the mentioned cygnet file are not listed in the requirements expressed [here](https://github.com/astropy/astropy/blob/master/docs/install.rst). I ll try to build astropy updating the requirements.

**Comment by dgrimreaper** [comment]
yeah it's tedious, but it ensures workflow provenance.  That's why I think this stuff should all be in containers, because those can be version controlled easily.

**Comment by Halolegend94** [comment]
Looks like that aplpy is not used at all since the modulefile points to empty directories on Magnus (please double check this). I believe we can remove this module at the moment and work on a proper strategy to install python modules.

> we can make the usage of pip more acceptable, if EVERY SINGLE package (including dependencies) that pip installs comes with a version specification. This can be achieved with a syntax like: pip install aplpy==2.0.3

I believe this is the way to go. Using pip without maali downloading from source if not necessary. On a high level,

1. compute the list of all python packages required along with constraints on their version
2. check which requirements are satisfied by modules already installed, and load them.
3. create a new python virtualenv and freeze it (i.e. list all currently installed packages)
4. run pip install by specifying the installation folder. All dependencies will be installed at the same location
5. freeze again the environment and compute the diff: this is the list of newly installed packages along with their version. Add to this list all the required modules that were already present.

To install again, take the list produced at point 5, load all the modules already installed, run pip install specifying constraints on dependencies generated from the rest of the list.

**Comment by marcodelapierre** [comment]
So two propositions here from you, which I personally both approve:

1. aplpy is currently not installed on the system (modulefile there, but no installation). No user has complained, so it looks like right now no one is using it.

Let us not bother reinstalling it for now

**Comment by marcodelapierre** [comment]
2. Your suggested protocol going forward for python pip packages. Only thing, I would consider still keeping it in a maali context.

Suggestion for discussion: after point 5 (differential list of packages) we might have a point 6. where we implement such list in a maali cygnet (source download can be skipped in maali).

It would be great to capture this propositions in a place we can track and share with the rest of the team, such as Confluence or a Jira Ticket (of type Supercomputing Applications possibly?)

Then we can bring it back on the table when we discuss policies on the software stack for the new system.

What do you think?

**Comment by Halolegend94** [comment]
I am going to create 2 tickets, one to remove aplpy module and one about python packages installation :)

**Comment by marcodelapierre** [comment]
perfect! closing this PR for now

**Comment by Halolegend94** [comment]
We need to remove the previous aplpy.cyg file which contains "404: Not Found."

**Comment by marcodelapierre** [comment]
done now!

**Pull request closed without merging**
