### PR TITLE
Update gromacs.cyg

### PR DESCRIPTION
**Pull request by ddeeptimahanti**

### CODE REVIEW

**Comment by marcodelapierre** [comment]
just keep in mind there's a nice GPU container on Nvidia GPU Cloud that works quite well.
IT's already downloaded and available on Topaz :)

**Review by Halolegend94 — CHANGES_REQUESTED** [review]
I suggest using ``MAALI_CUDA_BUILD_ONLY=1`` for this cygnet.

**Comment by ddeeptimahanti** [comment]
> just keep in mind there's a nice GPU container on Nvidia GPU Cloud that works quite well.
> It's already downloaded and available on Topaz :)

Yes Marco, the existing one is containerised module. Alec is helping someone with this new version so proposed this change

**Comment by marcodelapierre** [comment]
> > just keep in mind there's a nice GPU container on Nvidia GPU Cloud that works quite well.
> > It's already downloaded and available on Topaz :)
> 
> Yes Marco, the existing one is containerised module. Alec is helping someone with this new version so proposed this change

just be aware that 2020.2 is also available as container!

**Comment by ddeeptimahanti** [comment]
> > > just keep in mind there's a nice GPU container on Nvidia GPU Cloud that works quite well.
> > > It's already downloaded and available on Topaz :)
> > 
> > 
> > Yes Marco, the existing one is containerised module. Alec is helping someone with this new version so proposed this change
> 
> just be aware that 2020.2 is also available as container!

https://support.pawsey.org.au/portal/browse/GS-15964 - Marco do you want to comment there for Alec.

**Review by Halolegend94 — APPROVED** [review]

**Pull request merged**
