### PR TITLE
Update to h5py cygnet to handle building mpi version

### PR DESCRIPTION
**Pull request by pelahi**
update to cygnet to handle compiling mpi h5py.

### CODE REVIEW

**Review by ddeeptimahanti — APPROVED** [review]

**Review by marcodelapierre — CHANGES_REQUESTED** [review]
1. Lines 15-16 and 41-42: for improved clarity and reduced chances of errors, please do not repeat items across MAALI_TOOL_PREREQ and MAALI_TOOL_BUILD_PREREQ.
2. Line 56: get rid of cce, as the corresponding PrgEnv is not listed in line 49 above
3. Line 98 and following : as the COMPILER is not set to python any more, the function "maali_python_build" is not used and you can get rid of it
4. Feel free to delete lines that are commented out from the previous version of this cygnet (e.g. commented variable definitions

**Comment by pelahi** [comment]
Hi @marcodelapierre , happy to do most of changes but I feel like it is useful to leave in the  maali_python_build with the comments associated with it. In this way, the cygnet ends up as useful documentation. 
For example, why should items not be repeated in MAALI_TOOL_BUILD_PREREQ and MAALI_TOOL_PREREQ? Surely some modules fall under both categories (you want them as a prereq for the tool and are required for a build).

**Comment by Halolegend94** [comment]
I agree with Marco. Moreover, I think you have implemented some logic in maali_python_build that is not present in maali_build, for example, the build options for when it builds h5py-parallel

**Comment by pelahi** [comment]
The logic is the same, there is just a difference in how it is implemented since I was running into issues providing extra options when running the python install and thought the ideal work around was to export these build options.

**Comment by marcodelapierre** [comment]
@pelahi if you want to leave the other function and definitions for documentation, 
can you please state in commented lined that those are legacy, unmaintained snippets for documentation purposes only?

As regards MAALI_TOOL_BUILD_PREREQ and MAALI_TOOL_PREREQ, 
my/our bad in poorly documenting how maali works.
Their meaning&usage in maali is as follows:

MAALI_TOOL_PREREQ == used at build AND run time (i.e. ALL runtime modules are forcibly loaded at build time)
MAALI_TOOL_BUILD_PREREQ == used at build time ONLY

Your way works, but is more verbose, which I'd say implies less readable and more error prone (e.g. a version typo of the same module in the two definitions)

Does it make more sense?

**Review by marcodelapierre — APPROVED** [review]

**Comment by marcodelapierre** [comment]
clear to go for me, thanks Pascal!

**Pull request merged**
