### PR TITLE
Adds vasp.cyg

### PR DESCRIPTION
**Pull request by Halolegend94**
Adds vasp with gpu support. Note that the path to the source code is hard coded, maybe we can use an env variable.

### CODE REVIEW

**Comment by Halolegend94** [comment]
This patch actually has to be fixed since the source code is accessible only by malli user and all users in pawsey0001 group. How can we allow a group installation from a user? The source code must be accessible by that user.

**Comment by dgrimreaper** [comment]
Any user with a valid license can download the source code.  We should never be providing them the source code, even if they prove they have a license.  They will need to download the source and put in their own location as appropriate.

**Comment by Halolegend94** [comment]
Thanks for the help! I was reading the license to search for this information. I will modify the maali file accordingly.

**Comment by marcodelapierre** [comment]
yep, have a look at the maali cyg for magnus, that's the way
(basically you assume the source tar is already in the src/ directory location)

**Comment by marcodelapierre** [comment]
Commenting on my edits:
- modules that appear in MAALI_TOOL_PREREQ do not need to be repeated in MAALI_TOOL_BUILD_PREREQ. Both sets are loaded at build time, the difference is that the former are also loaded in the module file for production.
- prereqs: use module intel-tbb for tbb libraries
- prereqs: use openmpi-ucx-gpu (not openmpi-ucx), as we are building a gpu enabled tool
- as discussed, the compiler swap is dirty, but this makes it a bit less dirty: `module swap gcc $MAALI_COMPILER`

**Comment by Halolegend94** [comment]
Regarding the dirty switch.

GCC 7.2 gives the following error:
```
gcc -E -P -C -w mpi.F >mpi.f90 -DHOST=\"LinuxGNU\" -DMPI -DMPI_BLOCK=8000 -Duse_collective -DscaLAPACK -DCMAKE_Fortran_COMPILER_SUPPORTS_CONTIGUOUS=FALSE -DCACHE_SIZE=4000 -Davoidalloc -Duse_bse_te -Dtbdyn -Duse_shmem -DNGZhalf
mpif90 -ffree-form -ffree-line-length-none -w -O2 -I/pawsey/centos7.6/devel/cascadelake/gcc/8.3.0/fftw/3.3.8/include -c mpi.f90
mpif-sizeof.h:66:41:
Error: Array specification at (1) has more than 7 dimensions
mpif-sizeof.h:72:41:
```

and GCC 8.3 the following
```
gcc -E -P -C -w wave.F >wave.f90 -DHOST=\"LinuxGNU\" -DMPI -DMPI_BLOCK=8000 -Duse_collective -DscaLAPACK -DCMAKE_Fortran_COMPILER_SUPPORTS_CONTIGUOUS=FALSE -DCACHE_SIZE=4000 -Davoidalloc -Duse_bse_te -Dtbdyn -Duse_shmem -DNGZhalf
mpif90 -ffree-form -ffree-line-length-none -w -O2 -I/pawsey/centos7.6/devel/cascadelake/gcc/8.3.0/fftw/3.3.8/include -c wave.f90
wave.f90:1208:15:

     W1%CPTWFP=>W%CPTWFP(:,:,:,ISPIN)
               1
Error: Assignment to contiguous pointer from non-contiguous target at (1)
wave.f90:1209:15:


```

**Pull request merged**
