### PR TITLE
DualSPHysics cygnet file

### PR DESCRIPTION
**Pull request by AlexisEspinosaGayosso**
cygnet file prepared for Prof. Ryan Lowe (Oceans Institute UWA)
Ticket: GS-12249

### CODE REVIEW

**Comment by AlexisEspinosaGayosso** [comment]
This cygnet file was used for installing dualsphysics solver for project: pawsey0106
As requested by Prof. Ryan Lowe in ticket GS-12249

Installation was made only into that group fro zeus

**Comment by marcodelapierre** [comment]
Hi @AlexisEspinosaGayosso ,
I would get rid of 

"
  # tool build pre-requisites - not added to the module, only needed for building (loaded after MAALI_TOOL_PREREQ)
 MAALI_TOOL_BUILD_PREREQ="cuda/9.2"
"

You don't really need it is already loaded anyway.

Can you give me feedback on this aspect? Then I'll proceed with merging.

Thanks,

**Comment by AlexisEspinosaGayosso** [comment]
Agree, there is no need for the second prereq. The first one is still needed because, as you said, cuda/9.2 is not installed system wide.

I amended my commit and removed the second prereq from the file.

Please double check and, if you agree, you can proceed to merge.

Cheers.

**Comment by dgrimreaper** [comment]
I agree to remove it since you're using maali -n and have the explicit version set in the cuda compiler.
An alternative is to not set the MAALI_TOOL_CUDA_COMPILERS and instead have some documentation for the user to set this before running maali.  That will make porting to a new system easier later.

**Pull request merged**
