### PR TITLE
Updates gromacs cygnet and adds plumed2

### PR DESCRIPTION
**Pull request by Halolegend94**
gromacs
- Adds code (commented out) to patch with plumed
- Simplify cygnet file, removes double precision build which is not supported with gpu
- Fixes incorrect build options

plumed2, simply added cygnet file

### CODE REVIEW

**Comment by Halolegend94** [comment]
Also, now uses intel-mkl

**Comment by marcodelapierre** [comment]
doppia libidine! (cit. Jerry Calà)

**Comment by marcodelapierre** [comment]
thanks Cristian,
I am assuming you tested the build...? :-)

**Comment by Halolegend94** [comment]
The software was built successfully, I am waiting for a user to confirm it works properly!

**Comment by marcodelapierre** [comment]
Good, thanks. If you think the outcomes of the user tests will come reasonably soon (days?), it's probably worth waiting for those.

You may want to check yourself whether the gromacs and plumed executables work with a test command, eg --help

**Comment by marcodelapierre** [comment]
Oh, Cristian, 
I have just noticed that in this gromacs cygnet all plumed features ( build prereq and patching command) are commented out

Can you please double check?

**Comment by marcodelapierre** [comment]
Also, although of minor importance,

would it be possible to specify MPI for Gromacs NOT as a build prereq, but instead as MAALI_TOOL_MPI_COMPILERS ?

This is more of a best practice, allows easily adding builds with additional mpi versions

**Comment by Halolegend94** [comment]
Hi Marco,
1) gromacs/2021.2 is reported to work fine. Mark D'Agostino has just provided me with some test cases for plumed, I'll try them soon as possible.
2) Plumed is commented out because the latest versions of gromacs (e.g. 2021.2) are not yet officially supported. Thats why I have build 2020.4 with plumed, but not 2021.2.
3) Yes, definitely! I am on it

**Comment by marcodelapierre** [comment]
For point 2, How about inserting an IF on the Gromacs version, to enable/disable linking with Plumed?

**Comment by Halolegend94** [comment]
Hi Marco, the tool works well. I also added the if statement. check the last commit :)

**Comment by marcodelapierre** [comment]
Thanks Cristian! 

Just taking you back to the last outstanding point:

"would it be possible to specify MPI for Gromacs NOT as a build prereq, but instead as MAALI_TOOL_MPI_COMPILERS ?"

Do you reckon it's sensible to implement this suggestion? If so, please go ahead.

**Comment by Halolegend94** [comment]
Sorry for the late reply, Marco. I have set MPI as a compiler!

**Pull request merged**
